spring:
  application:
    name: job-service

server:
  port: 8702



### 数据源信息相关配置，多数据源支持，直接在最下面添加即可
datasources:
  default-db: default-db
  list:
    - dataSourceName: default-db
      enable: true
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.3.52:5432/hotel_v3_prd_wyn_test
      username: postgres
      password: dev@yjxd.com_euci
    - dataSourceName: db-bgy
      enable: true
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.3.52:5432/hotel_v3_prd_bgy_test
      username: postgres
      password: dev@yjxd.com_euci


eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8701/eureka/
  instance:
    # 更改服务名
    instance-id: ${spring.application.name}${server.port}
    # 显示服务IP地址
    prefer-ip-address: true
debug: true